theme: jekyll-theme-minimal
title: Theo Maffei
description: website
show_downloads: False
navigation:
  - title: Linkedin
    url: https://linkedin.com/in/theo-maffei-27a2232a8
  - title: Strava 
    url: https://www.strava.com/athletes/121452942

